version: '3.8'

services:
  api-reconhecimento:
    build: ./sinout-reconhecimento
    ports:
      - "5001:5000"
    volumes:
      - deepface_weights:/app/.deepface 
    restart: always

  api-processamento:
    build: ./Sinout-Processamento/Sinout
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - api-reconhecimento

volumes:
  deepface_weights: