services:
  # Serviço 1: API Sinout-Processamento (.NET)
  - type: web
    name: sinout-api-processamento
    env: docker
    rootDir: Sinout-Processamento/Sinout 
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:$PORT
    healthCheckPath: /health

  # Serviço 2: API Python (Reconhecimento)
  - type: web
    name: sinout-api-python
    env: docker
    rootDir: Sinout-Reconhecimento
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 5000
      - key: DEEPFACE_HOME
        value: /app/.deepface